/**************************************************************
* File Title: Dev Tool 1 Class Body
* Author: Brogan Avery
* Created :
 
 
* File Description : This class helps a developer improve there skills. It currently lets user choose from practice problems
***************************************************************/

#include "DevTool1.hpp"

DevTool1::DevTool1(){} ///constructor

void DevTool1::menu1(){
    string userInput = " ";
    cout << "\n* Skills Builder * " << endl;
    
    while (userInput != "2") {
        cout << "  Select number " << endl;
        cout << "     1. Practice Coding Problems" << endl;
        cout << "     2. Return To Developer Tools Dashboard" << endl;

        cout << "  Enter Selection: " << endl;
        cin >> userInput;

        if (userInput == "1"){
        }

        if (userInput == "2"){
        }
    }
    cout << "Going back to Dashboard..." << endl;
}

void DevTool1::displayProblems(){
    string userInput = " ";
    vector<string> lines = readFile("practiceCodeProblems.txt"); /// generated by python code, but moved to where C++ project other files are. contains links to online problems
    vector<string> problems;
    
    // puts just the problem names into a vector
    for (int i = 0; i < lines.size(); i+=2){
        problems.push_back(lines[i]);
    }
    
    cout << "Here is a list of names of different practice problems." << endl;
    cout << "To visit the description (as well as the solution) of a problem, enter the number associated with the problem when prompt." << endl;
    ///sleep(3);
    
    // prints list of problem names
    for (int i = 0; i < problems.size(); i++){
        cout << i + 1 << ". " << problems[i] << endl;
    }
    
    while (userInput != "0") {
        cout << "\nSelect problem number or to return to the previous screen, enter 0 " << endl;
        cout << "  Enter Selection: " << endl;
        cin >> userInput;
        
        // looks for matching problem in the vector
        for (int i = 0; i < problems.size(); i++){
            if (userInput == to_string(i + 1)){
                cout << problems[i] << endl;
            }
        }
    }
    cout << "Going back to Previous Menu Screen...\n" << endl;
}

